### ISSUE TITLE
Cannot pass a path with spaces

### ISSUE THREAD

**Issue by CoenraadS** [fabien0102/git2json#6]
I'm trying to use this on a file-path with spaces, but it does not work

https://github.com/fabien0102/git2json/blob/5b95a5768e7ece27da4ee812d8915d8432e704ef/src/git2json.js#L37-L38

**Comment by fabien0102** [comment]
True! Nice catch!
Fixed, and release on npm ;)

I have tested locally with a dump project:
```js
const git2json = require('@fabien0102/git2json');

git2json
  .run({path: "../project with spaces"})
  .then(json => console.log(json))
```

@CoenraadS can you confirm that is also working for you on `@fabien0102/git2json@1.3.1`?

**Comment by CoenraadS** [comment]
Thanks for quick fix. Working now 👍
